### ISSUE TITLE
Notice of Copyright/License Violation

### ISSUE THREAD

**Issue by Fuzzbawls** [syfares/Barandos#1]
This is an official notice of Copyright violation against the PIVX developers in which this project has been forked from. The MIT copyright license, and subsequent copyright headers in source files have been modified to explicitely exclude the PIVX developers.

You are hereby notified of an intention to pursue further action if this issue is not acknowledged and formally addressed with a resolution timeframe commitment wherein. Failure to acknowledge and correct the violation will result in a formal DMCA takedown notice filed with GitHub Proper after no less than five business days from the date of this notice.

Explicit acknowledgement and referencing progress to maintain compliance MUST be noted in this issue's comments or referred to in any subsequent pull requests to this repository.

**Comment by syfares** [comment]
Hi,

Don't worry, this is just the standard replace at work, all copyright will be added before any real release (if it ever happen :) )

**Comment by syfares** [comment]
Well it was easier than i thought !
Let me know if it is ok for you as well so i can close the issue

**Comment by Fuzzbawls** [comment]
`.ccp` and `.h` headers look ok, don't forget https://github.com/syfares/Barandos/blob/master/COPYING though. After that file is updated then issue resolved :)

**Comment by syfares** [comment]
Done !
